local Door =require(game:GetService("Players").riucnb1.Backpack["Door-Door"].Data)
Door:Cooldown(1000)

game:GetService("Workspace").MobsHolder.Demon3.HumanoidRootPart


local mobs = game:GetService("Workspace").MobsHolder;


function getCurrentPlayerPOS()
    local player = game.Players.LocalPlayer;
    if player.Character then
    return player.Character.HumanoidRootPart.Position;
    end
    return false; 
end

function teleportTo(placeCFrame)
    local player = game.Players.LocalPlayer;
    if player.Character then
        player.Character.HumanoidRootPart.CFrame = placeCFrame;
    end 
end


function teleportMobs(mobs)
    if game:GetService("Workspace").MobsHolder.Slayer2 then
        teleportTo(game:GetService("Workspace").MobsHolder.Slayer2.HumanoidRootPart.CFrame) 

    end
end


for i,v in next, game:GetService("Workspace").MobsHolder:FindFirstChild() do 
    if v then 
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = v.HumanoidRootPart.CFrame; 
    wait(.5)
    end
    end

   
    for i, v in next, game:GetService("Workspace").MobsHolder:GetChildren()do
        if v then
        getgenv().aFarm = false
        while aFarm == true do
                local me = game.Players.LocalPlayer.Character
                local pos = v.HumanoidRootPart
                me.HumanoidRootPart.CFrame = 
                CFrame.new(pos.Position.X-0, pos.Position.Y+15, pos.Position.Z+20)
                wait()
                end
        end
        if aFarm == false then break end
        end
        
        -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

workspace.cfvip789.Hatchet.Throw:FireServer()

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

workspace.cfvip789.Hatchet.Throw:FireServer()
    

if _G.nododgecool then
    for i,v in next, getgc() do
        if workspace.cfvip789.Hatchet.Throw then
            if typeof(v) == "function" and getfenv(v).script == workspace.cfvip789.Hatchet.Throw then
                for i2,v2 in next, getupvalues(v) do
                    if tostring(v2) == "0.4" then
                        repeat wait()
                            setupvalue(v,i2,0)
                        until not _G.nododgecool
                    end
                end
            end
        end
    end
end

local h = require(game:GetService("Players").cfvip789.StarterGear.Hatchet.Remote)
h:Throw()

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Dodge"
local ohNil2 = nil
local ohNumber3 = 30
local ohBoolean4 = false

game:GetService("ReplicatedStorage").Remotes.CommE:FireServer(ohString1, ohNil2, ohNumber3, ohBoolean4)

workspace.Characters.riucnb1.Movement

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "IceWalk"
local ohVector32 = -1701.7811279297, 0.18983209133148, -1239.58984375

game:GetService("ReplicatedStorage").Remotes.CommE:FireServer(ohString1, ohVector32)


-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "FromTraining"
local ohNumber2 = 1

game:GetService("ReplicatedStorage").RemoteEvent.AddPowerEvent:FireServer(ohString1, ohNumber2)
game:GetService("Workspace").riucnb1.HumanoidRootPart